service:
    name: hello-world
    config:
      accountId: accid 
      zoneId: zoneid 
      scripts:
        helloworld:
          routes:
            - example.com/*
            - example.com/hi/*

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    script: helloworld
    handler: helloWorld
