service:
    name: hello-world
    config:
      accountId: accid 
      zoneId: zoneid
      routes:
        - 'example.com/hello*'
        - 'example.com/world*'


provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    handler: helloWorld
