service:
    name: hello-world
    config:
      accountId: abcdefghijklmnopqrstuvwxyz123456
      zoneId: abcdefghijklmnopqrstuvwxyz123456
      scripts:
        helloworld:
          routes:
            - example.com/hello/*
        goodbyeworld:
          routes:
            - example.com/goodbye/*

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    script: helloworld
    handler: helloWorld

  goodbyeWorld:
    script: goodbyeworld
    handler: goodbyeWorld