service:
    name: hello-world
    config:
      accountId: 5ea9ff246c8fd83268943de928d5109a
      zoneId: 66de06a610e659edd89a6de59df291d2
      workers:
        hello:
          routes:
            - nirvik.me/boo/*

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    worker: hello
    script: helloWorld  # there must be a file called helloWorld.js
