service:
    name: hello-world
    config:
      accountId: accid 
      zoneId: zoneid
      scripts:
        hello:
          routes:
            - 'example.com/hello*'
        goodbye:
          routes:
            - 'example.com/goodbye*'


provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    script: hello
    handler: helloWorld

  bye:
    script: goodbye
    handler: goodByeWorld
