service:
    name: hello-world
    config:
      accountId: 5ea9ff246c8fd83268943de928d5109a 
      zoneId: 66de06a610e659edd89a6de59df291d2
      scripts:
        one:
          routes:
            - nirvik.me/good/*
        two:
          routes:
            - nirvik.me/boy/*

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    script: one
    fn: handler.helloCloudflarian
    id: helloCloudflarian
    name: say hello
    description: Please say hello
    schema:
      type: object
      properties:
    values:
    events:
      - http:
          query:
            bar: hello

  getBTC:
    script: two
    fn: handler.bitcoin
    id: bitcoin
    name: getBTC
    description: get bitcoin prices
    schema:
      type: object
      properties:
    values:
    events:
      - http:
          query:
            bar: btc
