service:
    name: hello-world
    config:
      accountId: e04d3d27a6829775c8ef937145d7f3ec 
      zoneId: d0ff429e46e8b24ef2b1ae9ba592067f
      scripts:
        hello:
          routes:
            - '*averyharnish.com/hello*'
        goodbye:
          routes:
            - '*averyharnish.com/goodbye*'


provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  helloWorld:
    script: hello
    handler: helloworld

  getBTC:
    script: goodbye
    handler: goodbyeworld
